### ISSUE TITLE
Investigate how we're going to test the performance of the plugin

### ISSUE THREAD

**Issue by jyoo980** [jyoo980/silver#16]
I'll have a chat with Alex about testing this

**Comment by ionathanch** [comment]
Could you also ask him to provide some Prusti example that produces a bunch of predicates? It'd be useful for the motivation section
(It'd be great if we could actually run our plugin on a Prusti example, but idk how much work that would be to set up)

**Comment by jyoo980** [comment]
Sure we can ask as soon as he replies on Slack lol. Could also bug him during scrum tmrw
